### ISSUE TITLE
Mark xenv-0.0.4-py_0.tar.bz2 as broken

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/xenv-feedstock#3]
@conda-forge/core Can someone mark `noarch/xenv-0.0.4-py_0.tar.bz2` as broken please? It uses `2to3` in the build despite being marked as `noarch` making the package unusable with Python 3.

https://anaconda.org/conda-forge/xenv/files?version=0.0.4

**Comment by ocefpaf** [comment]
Done! Can you check if I got it right?

https://anaconda.org/conda-forge/xenv/files?channel=broken

**Comment by chrisburr** [comment]
Perfect, thanks @ocefpaf 🍰
